apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-store
  template:
    metadata: 
      labels:
        app: service-store
    spec:
      containers:
      - name: service-store
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi